// codegen-timing.ts — emits client/scripts/generated/Timing.gd from the
// canonical TS timing module. Per FINAL_GOAL §A4, timing.ts is the single
// source of truth; Godot can't import TypeScript so we transcribe the
// numbers into a GDScript autoload at build time. Run via:
//
//     pnpm codegen:timing
//
// CI runs this on push and fails if the regenerated file differs from the
// committed Timing.gd, catching drift between the TS sim/server and the
// Godot client.
//
// The output layout is fixed (this script's job is to make Timing.gd
// byte-for-byte reproducible) so a `git diff --exit-code` after a clean
// regen exits 0.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  PHASE_T_REVEAL,
  PHASE_T_PREP,
  PHASE_T_RUSH,
  PHASE_T_PULL_PANTS,
  PHASE_T_STRIKE,
  PHASE_T_IMPACT,
  ACTION_TOTAL_MS,
  ROUND_TOTAL_MS,
  TIE_NARRATION_HOLD_MS,
  SHAME_FRAME_HOLD_MS,
  ZOOM_IN_DUR_MS,
  ZOOM_HOLD_MS,
  ZOOM_OUT_DUR_MS,
  ZOOM_TARGET,
  WINNER_CHOICE_BUDGET_MS,
  PICKER_AUTO_PICK_MS,
} from "../src/game/timing.js";

// Format a float for GDScript such that 1.6 → "1.6" (one trailing decimal)
// rather than "1.6000000000". GDScript accepts either, but the committed
// Timing.gd uses the short form so we match it for byte-stability.
function fmtFloat(n: number): string {
  if (Number.isInteger(n)) return n.toFixed(1);
  return String(n);
}

const HEADER = `# GENERATED — do not edit. Source: shared/src/game/timing.ts
#
# This file is regenerated by \`pnpm codegen:timing\` (S-006). Manual edits
# will be overwritten. Constants here MUST stay in lockstep with the
# canonical TS module — CI fails on drift.
#
# Phase timeline (FINAL_GOAL §A4):
#   REVEAL     1500ms  [    0 →  1500]   simultaneous throw glyphs
#   PREP        300ms  [ 1500 →  1800]   anticipation crouch
#   RUSH        600ms  [ 1800 →  2400]   sprint to victim with dust
#   PULL_PANTS  900ms  [ 2400 →  3300]   the 扒裤衩 reveal
#   STRIKE      600ms  [ 3300 →  3900]   knife wind-up + chop
#   IMPACT      800ms  [ 3900 →  4700]   shake + wood chip burst
#                      ─────
#                       4700ms = ROUND_TOTAL_MS
#                       3200ms = ACTION_TOTAL_MS  (PREP→IMPACT segment)
`;

const lines: string[] = [];
lines.push(HEADER.trimEnd()); // header block, no trailing blank yet
lines.push(""); // blank
lines.push("extends Node");
lines.push("");
lines.push(`const PHASE_T_REVEAL: int = ${PHASE_T_REVEAL}`);
lines.push(`const PHASE_T_PREP: int = ${PHASE_T_PREP}`);
lines.push(`const PHASE_T_RUSH: int = ${PHASE_T_RUSH}`);
lines.push(`const PHASE_T_PULL_PANTS: int = ${PHASE_T_PULL_PANTS}`);
lines.push(`const PHASE_T_STRIKE: int = ${PHASE_T_STRIKE}`);
lines.push(`const PHASE_T_IMPACT: int = ${PHASE_T_IMPACT}`);
lines.push(`const ACTION_TOTAL_MS: int = ${ACTION_TOTAL_MS}`);
lines.push(`const ROUND_TOTAL_MS: int = ${ROUND_TOTAL_MS}`);
lines.push(`const TIE_NARRATION_HOLD_MS: int = ${TIE_NARRATION_HOLD_MS}`);
lines.push(`const SHAME_FRAME_HOLD_MS: int = ${SHAME_FRAME_HOLD_MS}`);
lines.push("");
lines.push("# Camera cinematic timing (FINAL_GOAL §C2). Held here so Camera.gd and");
lines.push("# AnimationPlayer tracks share one source. ZOOM_OUT happens after IMPACT.");
lines.push(`const ZOOM_IN_DUR_MS: int = ${ZOOM_IN_DUR_MS}`);
lines.push(`const ZOOM_HOLD_MS: int = ${ZOOM_HOLD_MS}`);
lines.push(`const ZOOM_OUT_DUR_MS: int = ${ZOOM_OUT_DUR_MS}`);
lines.push(`const ZOOM_TARGET: float = ${fmtFloat(ZOOM_TARGET)}`);
lines.push("");
lines.push("# Winner-choice budget (FINAL_GOAL §H3 / §C10).");
lines.push(`const WINNER_CHOICE_BUDGET_MS: int = ${WINNER_CHOICE_BUDGET_MS}`);
lines.push(`const PICKER_AUTO_PICK_MS: int = ${PICKER_AUTO_PICK_MS}`);

const body = lines.join("\n") + "\n";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "../../client/scripts/generated/Timing.gd");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body, { encoding: "utf8" });

// Stay quiet on success so a CI runner sees a clean log; print path only.
console.log(`codegen:timing → ${outPath}`);
